language: go
go:
  - 1.6

before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libopus-dev -y

install: make
script: ./scripts/test.sh
